### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'estimator'

### ISSUE THREAD

**Issue by cirosantilli** [GantMan/nsfw_model#160]
Clone repo at 699b6796a55604341fbfdffe2b27ced1d868c591 then try to run on a clean virtualenv:

tmp.py

```
#!/usr/bin/env python
from nsfw_detector import predict
model = predict.load_model('mobilenet_v2_140_224')
predict.classify(model, 'tmp.jpg')
```

blows up with:

```
2024-03-24 07:41:21.502070: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-24 07:41:21.502308: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-24 07:41:21.504877: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-24 07:41:21.533738: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-24 07:41:22.045317: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/ciro/tmp/nsfw_model/./tmp.py", line 2, in <module>
    from nsfw_detector import predict
  File "/home/ciro/tmp/nsfw_model/nsfw_detector/predict.py", line 11, in <module>
    import tensorflow_hub as hub
  File "/home/ciro/tmp/nsfw_model/.venv/lib/python3.11/site-packages/tensorflow_hub/__init__.py", line 88, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/home/ciro/tmp/nsfw_model/.venv/lib/python3.11/site-packages/tensorflow_hub/estimator.py", line 62, in <module>
    class LatestModuleExporter(tf.compat.v1.estimator.Exporter):
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ciro/tmp/nsfw_model/.venv/lib/python3.11/site-packages/tensorflow/python/util/module_wrapper.py", line 232, in _getattr
    attr = getattr(self._tfmw_wrapped_module, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'estimator'
```

Ubuntu 23.10, Python 3.11.6.

`pip freeze` contains:

```
absl-py==2.1.0                                                                                 
astunparse==1.6.3                                                                                                                                                                             
certifi==2024.2.2                                                                              
charset-normalizer==3.3.2                                                                      
flatbuffers==24.3.25                                                                                                                                                                          
gast==0.5.4                                   
google-pasta==0.2.0                                                                            
grpcio==1.63.0                                                                                 
h5py==3.11.0                                                                                   
idna==3.7                                                                                      
keras==3.3.3                                                                                   
libclang==18.1.1                                                                               
Markdown==3.6                                                                                  
markdown-it-py==3.0.0                                                                          
MarkupSafe==2.1.5                                                                              
mdurl==0.1.2                                                                                                                                                                                  
ml-dtypes==0.3.2                                                                                                                                                                              namex==0.0.8                                                                                                                                                                                  
numpy==1.26.4                                                                                                                                                                                 
opt-einsum==3.3.0                                                                                                                                                                             
optree==0.11.0                                                                                                                                                                                
packaging==24.0                                                                                                                                                                               
pillow==10.3.0                                                                                                                                                                                
protobuf==4.25.3                                                                                                                                                                              
Pygments==2.17.2                                                                                                                                                                              
requests==2.31.0                                                                               
rich==13.7.1                                                                                   
six==1.16.0                                   
tensorboard==2.16.2                                                                                                                                                                           
tensorboard-data-server==0.7.2                                                                 
tensorflow==2.16.1                                                                                                                                                                            
tensorflow-hub==0.12.0                                                                         
tensorflow-io-gcs-filesystem==0.37.0                                                           
termcolor==2.4.0                                                                                                                                                                              
typing_extensions==4.11.0                                                                      
urllib3==2.2.1                                                                                 
Werkzeug==3.0.2                                                                                
wrapt==1.16.0 
```

**Comment by ibrahemdhade33** [comment]
same issue here

**Comment by Winvoker** [comment]
Did you find any solution? 

Edit : works with python 3.6 and tensorflow==2.2.0

**Comment by cirosantilli** [comment]
> Edit : works with python 3.6 and tensorflow==2.2.0

Ah nice! Maintainers made the fatal mistake of using `>=` on `requirements.txt`: https://github.com/GantMan/nsfw_model/blob/699b6796a55604341fbfdffe2b27ced1d868c591/requirements.txt#L1

**Comment by cirosantilli** [comment]
That's annoying, on Python 3.11.6 I get:

```
$ pip install tensorflow==2.2.0
ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.0 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.0.post1, 2.15.1, 2.16.0rc0, 2.16.1)
ERROR: No matching distribution found for tensorflow==2.2.0
```

so you really have to go down the Python version... and `pyenv install 3.6.0` segfaults...

**Comment by spydr1** [comment]
my solution 
`
pip install tf-keras==2.16.0 tensorflow-hub==0.16.0
`
Tensorflow has some change about keras. (keras 2 -> keras3)
There is migration issue.

**Comment by johnwesleysa** [comment]
Working with venv in Python 3.10.0 and pip install tf-keras==2.16.0 tensorflow-hub==0.16.0. 
Here’s the pip freeze output from the virtual environment:

absl-py==2.1.0
asttokens==2.4.1
astunparse==1.6.3
certifi==2024.8.30
charset-normalizer==3.4.0
colorama==0.4.6
comm==0.2.2
debugpy==1.8.7
decorator==5.1.1
exceptiongroup==1.2.2
executing==2.1.0
flatbuffers==24.3.25
gast==0.6.0
google-pasta==0.2.0
grpcio==1.67.1
h5py==3.12.1
idna==3.10
ipykernel==6.29.5
ipython==8.29.0
jedi==0.19.1
jupyter_client==8.6.3
jupyter_core==5.7.2
keras==3.6.0
libclang==18.1.1
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib-inline==0.1.7
mdurl==0.1.2
ml-dtypes==0.4.1
namex==0.0.8
nest-asyncio==1.6.0
numpy==2.0.2
opt_einsum==3.4.0
optree==0.13.0
packaging==24.1
parso==0.8.4
pillow==11.0.0
platformdirs==4.3.6
prompt_toolkit==3.0.48
protobuf==5.28.3
psutil==6.1.0
pure_eval==0.2.3
Pygments==2.18.0
python-dateutil==2.9.0.post0
pywin32==308
pyzmq==26.2.0
requests==2.32.3
rich==13.9.4
six==1.16.0
stack-data==0.6.3
tensorboard==2.18.0
tensorboard-data-server==0.7.2
tensorflow==2.18.0
tensorflow-hub==0.12.0
tensorflow-io-gcs-filesystem==0.31.0
tensorflow_intel==2.18.0
termcolor==2.5.0
tornado==6.4.1
traitlets==5.14.3
typing_extensions==4.12.2
urllib3==2.2.3
wcwidth==0.2.13
Werkzeug==3.1.2
wrapt==1.16.0

**Comment by zlao3118** [comment]
> Did you find any solution?
> 
> Edit : works with python 3.6 and tensorflow==2.2.0

I tried this version but got the following error:

2024-12-12 03:29:16.214472: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2024-12-12 03:29:16.214624: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING:tensorflow:From D:\pyenv\pyenv-win\versions\3.6.0\lib\site-packages\tensorflow\python\compat\v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:tensorflow:From D:\pyenv\pyenv-win\versions\3.6.0\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From D:\pyenv\pyenv-win\versions\3.6.0\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:1817: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2024-12-12 03:29:20.142553: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2024-12-12 03:29:20.166981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GTX 1660 Ti computeCapability: 7.5
coreClock: 1.59GHz coreCount: 24 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 268.26GiB/s
2024-12-12 03:29:20.167920: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2024-12-12 03:29:20.168684: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2024-12-12 03:29:20.169462: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2024-12-12 03:29:20.170224: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2024-12-12 03:29:20.170985: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2024-12-12 03:29:20.171747: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2024-12-12 03:29:20.172507: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2024-12-12 03:29:20.172687: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2024-12-12 03:29:20.173024: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2024-12-12 03:29:20.182327: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x23e5e11c7b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-12-12 03:29:20.182502: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-12-12 03:29:20.182825: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-12-12 03:29:20.183006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]
2024-12-12 03:29:21.615548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-12-12 03:29:21.615772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]
Traceback (most recent call last):
  File "start.py", line 19, in <module>
    result = predict.classify(model, [image_file])
  File "E:\nsfw_model\nsfw_model\nsfw_detector\predict.py", line 66, in classify
    images, image_paths = load_images(input_paths, (image_dim, image_dim))
  File "E:\nsfw_model\nsfw_model\nsfw_detector\predict.py", line 32, in load_images
    if isdir(image_paths):
TypeError: _isdir: path should be string, bytes or os.PathLike, not list

-------------------------------------------------------------------------------------------------------------------------------------

using：

absl-py                1.4.0
astunparse             1.6.3
cachetools             4.2.4
certifi                2024.8.30
charset-normalizer     2.0.12
colorama               0.4.5
dataclasses            0.8
gast                   0.3.3
google-auth            1.35.0
google-auth-oauthlib   0.4.6
google-pasta           0.2.0
grpcio                 1.48.2
h5py                   2.10.0
idna                   3.10
importlib-metadata     4.8.3
importlib-resources    5.4.0
Keras-Preprocessing    1.1.2
Markdown               3.3.7
numpy                  1.18.5
oauthlib               3.2.2
opt-einsum             3.3.0
pip                    21.3.1
protobuf               3.19.6
pyasn1                 0.5.1
pyasn1-modules         0.3.0
requests               2.27.1
requests-oauthlib      2.0.0
rsa                    4.9
scipy                  1.4.1
setuptools             59.6.0
six                    1.17.0
tensorboard            2.2.2
tensorboard-plugin-wit 1.8.1
tensorflow             2.2.0
tensorflow-estimator   2.2.0
tensorflow-hub         0.12.0
termcolor              1.1.0
tqdm                   4.64.1
typing_extensions      4.1.1
urllib3                1.26.20
Werkzeug               2.0.3
wheel                  0.37.1
wrapt                  1.16.0
zipp                   3.6.0
