### ISSUE TITLE
ValueError: Argument(s) not recognized: {'lr': 8.999999749903509e-07}

### ISSUE THREAD

**Issue by Fr333m4n** [GantMan/nsfw_model#164]
Hello,

I've tried the python script with given models in the readme, but I always have this error message.

```
D:\Downloads\!yyy\!dev\nsfw_model-1.2.0\nsfw_detector>py predict.py --saved_model_path nsfw_mobilenet2.224x224.h5 --image_source test.jpg
2024-09-11 07:11:57.432553: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-11 07:11:58.571961: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-09-11 07:12:00.793081: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\optimizers\base_optimizer.py:33: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(
Traceback (most recent call last):
  File "D:\Downloads\!yyy\!dev\nsfw_model-1.2.0\nsfw_detector\predict.py", line 112, in <module>
    main()
  File "D:\Downloads\!yyy\!dev\nsfw_model-1.2.0\nsfw_detector\predict.py", line 106, in main
    model = load_model(config['saved_model_path'])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\!yyy\!dev\nsfw_model-1.2.0\nsfw_detector\predict.py", line 55, in load_model
    model = tf.keras.models.load_model(model_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\saving\saving_api.py", line 194, in load_model
    return legacy_h5_format.load_model_from_hdf5(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 155, in load_model_from_hdf5
    **saving_utils.compile_args_from_training_config(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 133, in compile_args_from_training_config
    optimizer = optimizers.deserialize(optimizer_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\optimizers\__init__.py", line 65, in deserialize
    return serialization_lib.deserialize_keras_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\saving\serialization_lib.py", line 581, in deserialize_keras_object
    return deserialize_keras_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\saving\serialization_lib.py", line 718, in deserialize_keras_object
    instance = cls.from_config(inner_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 902, in from_config
    return cls(**config)
           ^^^^^^^^^^^^^
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\optimizers\sgd.py", line 60, in __init__
    super().__init__(
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\backend\tensorflow\optimizer.py", line 22, in __init__
    super().__init__(*args, **kwargs)
  File "D:\Apps\0-lib\Python312\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 37, in __init__
    raise ValueError(f"Argument(s) not recognized: {kwargs}")
ValueError: Argument(s) not recognized: {'lr': 8.999999749903509e-07}
```

Any Idea of what I'm doing wrong?

**Comment by NatanB4** [comment]
same problem here

**Comment by AdamBaverman** [comment]
Using some AI hints, I solved the same problem at my project. Here is a summary for solving the problem.
---

### Issue with Model Loading Using .h5 File
You encountered an error when loading a model from a `.h5` file due to the use of the deprecated argument `lr` in the optimizer. In recent versions of TensorFlow and Keras, the `lr` argument has been replaced with `learning_rate`. This change may cause issues when loading models saved with older library versions.

---

### Python Code for Loading and Predicting with NSFW Model

```python
from keras.layers import TFSMLayer
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# Load the model
model = TFSMLayer('/path_to_model', call_endpoint='serving_default')

# Labels from labels.txt
labels = ["drawings", "hentai", "neutral", "porn", "sexy"]

# Function to load and preprocess the image
def preprocess_image(image_path):
    # Load the image and resize it to 224x224
    img = load_img(image_path, target_size=(224, 224))
    # Convert to numpy array and normalize pixel values
    img_array = img_to_array(img) / 255.0
    # Add batch dimension (1, 224, 224, 3)
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

# Path to the image
image_path = 'XXX.jpg'
input_data = preprocess_image(image_path)

# Run the image through the model
output = model(input_data)

# Extract probabilities
probabilities = output['output_0'].numpy()[0]
# Adjusting to a real key
# Use the real key found in output.keys(), for example, "StatefulPartitionedCall" or "dense_3"
#(uncomment this)
#key = list(output.keys())[0]  # Presumably, we take the first key displayed in diagnostics
#probabilities = output[key].numpy()[0]

# Map class labels to probabilities
results = dict(zip(labels, probabilities))

# Print the results
print("Class probability distribution:")
for label, probability in results.items():
    print(f"{label}: {probability:.4f}")

# Determine the class with the highest probability
predicted_class = labels[np.argmax(probabilities)]
print(f"\nPredicted class: {predicted_class}")
```

---

### Notes:
1. **Model Compatibility**:
   - If the `.h5` file was saved with older versions of Keras or TensorFlow, ensure you convert or update the model to align with the current library versions.
   - Replace `lr` with `learning_rate` in the optimizer configuration if needed.

2. **Image Preprocessing**:
   - The code resizes images to `224x224` and normalizes pixel values to a range of `0-1`, which is typical for NSFW models.

3. **Inference**:
   - Probabilities are extracted from the model's output and matched with their respective class labels.

4. **Dependencies**:
   - Ensure `tensorflow` and `keras` are installed in your environment.
   - Replace `'XXX.jpg'` with the path to your input image.

---

### Example Output:
```
Class probability distribution:
drawings: 0.0000
hentai: 0.0000
neutral: 0.0000
porn: 0.9716
sexy: 0.0284

Predicted class: porn
```
