### ISSUE TITLE
Can't load model ('className' and 'config' must set.)

### ISSUE THREAD

**Issue by link-discord** [GantMan/nsfw_model#79]
'className' and 'config' must set.
       at new ValueError (/home/link/bots/anti-nsfw/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:186:28)
       at deserializeKerasObject (/home/link/bots/anti-nsfw/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:429:19)
       at deserialize (/home/link/bots/anti-nsfw/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:4959:12)
       at /home/link/bots/anti-nsfw/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:10439:29
       at step (/home/link/bots/anti-nsfw/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:104:23)
       at Object.next (/home/link/bots/anti-nsfw/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:85:53)
       at fulfilled (/home/link/bots/anti-nsfw/node_modules/@tensorflow/tfjs-layers/dist/tf-layers.node.js:75:58)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:93:5)

Code: 
`client.model = await nsfwjs.load('https://alert-tidal-flavor.glitch.me/model/')`

**Comment by sinhpn92** [comment]
I have same issue. How did you solve?
