### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by 1Euro7Cent** [GantMan/nsfw_model#98]
I got his error while trying to train some data.
Here is the image folder:
![image](https://user-images.githubusercontent.com/67194495/138413837-0255467a-da17-4ead-abff-551ef96f2e82.png)

in the nsfw folder are 177 png files
in the sfw folder are 284 png files

I use so "few" bc I want to test first before I get more traindata

```2021-10-22 09:40:33.989623: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-10-22 09:40:33.989777: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-10-22 09:40:35.924052: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-10-22 09:40:35.924806: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2021-10-22 09:40:35.925595: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2021-10-22 09:40:35.926285: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2021-10-22 09:40:35.926979: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2021-10-22 09:40:35.927668: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusolver64_11.dll'; dlerror: cusolver64_11.dll not found
2021-10-22 09:40:35.928368: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2021-10-22 09:40:35.929087: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021-10-22 09:40:35.929203: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Using hparams:
        train_epochs : 9001
        do_fine_tuning : True
        batch_size : 32
        learning_rate : 0.005
        momentum : 0.9
        dropout_rate : 0.0
        label_smoothing : 0.0
        validation_split : 0.1
        optimizer : rmsprop
        adadelta_rho : 0.95
        adagrad_initial_accumulator_value : 0.1
        adam_beta1 : 0.9
        adam_beta2 : 0.999
        opt_epsilon : 1.0
        ftrl_learning_rate_power : -0.5
        ftrl_initial_accumulator_value : 0.1
        ftrl_l1 : 0.0
        ftrl_l2 : 0.0
        rmsprop_momentum : 0.0
        rmsprop_decay : 0.9
        do_data_augmentation : True
        use_mixed_precision : True
I1022 09:40:35.938430  9192 resolver.py:78] Using C:\Users\Thoma\AppData\Local\Temp\tfhub_modules to cache modules.
2021-10-22 09:40:36.087134: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Using module https://tfhub.dev/google/imagenet/mobilenet_v2_140_224/feature_vector/4 with image size (224, 224)
Traceback (most recent call last):
  File "C:\Users\Thoma\Documents\nsfw detector model\training\make_nsfw_model.py", line 336, in <module>
    run_main()
  File "C:\Users\Thoma\Documents\nsfw detector model\training\make_nsfw_model.py", line 332, in run_main
    app.run(main)
  File "C:\Users\Thoma\AppData\Local\Programs\Python\Python39\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\Thoma\AppData\Local\Programs\Python\Python39\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "C:\Users\Thoma\Documents\nsfw detector model\training\make_nsfw_model.py", line 259, in main
    model, labels, train_result, frozen_graph = lib.make_image_classifier(
  File "C:\Users\Thoma\Documents\nsfw detector model\training\make_nsfw_model_lib.py", line 508, in make_image_classifier
    train_data_and_size, valid_data_and_size, labels = _get_data_with_keras(
  File "C:\Users\Thoma\Documents\nsfw detector model\training\make_nsfw_model_lib.py", line 200, in _get_data_with_keras
    valid_generator = valid_datagen.flow_from_directory(
  File "C:\Users\Thoma\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\preprocessing\image.py", line 976, in flow_from_directory
    return DirectoryIterator(
  File "C:\Users\Thoma\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\preprocessing\image.py", line 394, in __init__
    super(DirectoryIterator, self).__init__(
  File "C:\Users\Thoma\AppData\Local\Programs\Python\Python39\lib\site-packages\keras_preprocessing\image\directory_iterator.py", line 115, in __init__
    for subdir in sorted(os.listdir(directory)):
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Thoma\\Documents\\nsfw'
```

`Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Thoma\\Documents\\nsfw' ` translates to: `the system cannot find the given path:  'C:\\Users\\Thoma\\Documents\\nsfw'`

**Comment by colindean** [comment]
If this is still a problem, please provide the version of nsfw_detector that you're using, your Python version, your Python platform, and a code example of how you're invoking nsfw_detector, and reopen the issue.
